modLoader="javafml"
loaderVersion="[47,)"
license="GNU GPL v3.0"
[[mods]] #mandatory
modId="nomoonnoproblem"
version="1.0"
displayName="No Moon, No Problem (Goety Necroturgy Mixin)"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="Moon_Phases.gif"
authors="hallowfiend"
description='''Fixes Goety's Necroturgy ritual to work in dimensions where the concept of moon and sun do not apply'''
[[dependencies.nomoonnoproblem]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomoonnoproblem]]
    modId="minecraft"
    mandatory=true
    versionRange="1.20.1"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomoonnoproblem]]
    modId="goety"
    mandatory=true
    versionRange="[1.20-2.5,)"
    ordering="AFTER"
    side="BOTH"
